Add REPL function
mandeep/sublime-text-conda pull request #27
Opened 2020-06-27 15:49 UTC by titus-ong

SublimeREPL unfortunately doesn't work with Conda environments in a simple manner - you'd have to create a new build or constantly change the interpreter for different environments. I added an "Open REPL" command (mostly taken from stackoverflow and edited to fit the Conda context) - the command uses the interpreter of the active environment and opens a REPL window for the currently opened file. 

It's quite simple but I think it'll be useful. Ideally, I would like the REPL to be reusable i.e. if you run the command repeatedly for the same environment, the same REPL window is updated, but currently a new window is opened each time. It seemed that the way SublimeREPL achieved that was in a rather complicated way though, so I'll see if I can implement that in the future.

2020-06-28 05:53 UTC, mandeep commented
Thanks for the PR! I will test it this weekend and let you know how it goes.

2020-07-10 10:15 UTC, titus-ong commented
Hey @mandeep, was wondering if there were any issues you faced for this and the other PR?

2020-07-12 15:58 UTC, mandeep commented
@titus-ong I haven't had a chance to review the PRs yet. Hopefully I can get to them today.

2020-07-29 23:20 UTC, mandeep requested changes

2020-07-29 23:20 UTC, mandeep commented on commands.py
> +        executable_path = "{}\\{}".format(os.path.expanduser(environment_path), "python")
Unfortunately this \\ on line 250 will cause problems on Linux systems. You'll want to use `os.sep` here for a cross-platform separator.

2020-07-30 04:57 UTC, mandeep commented on commands.py
> +        executable_path = "{}\\{}".format(os.path.expanduser(environment_path), "python")
I think this could be `os.path.join(os.path.expanduser(environment_path, "python")`.

2020-07-30 19:30 UTC, mandeep commented
@titus-ong thanks for your contribution. I pushed a view small changes to your branch that should fix some issues. Great work!

2020-07-30 19:30 UTC, merged

2020-07-31 05:42 UTC, titus-ong commented
Thanks for the changes, wasn't aware of that.