REPL fixes and improvements
mandeep/sublime-text-conda pull request #29
Opened 2020-09-19 17:24 UTC by gseastream

# Summary

Sorry for the second pull request. I just discovered a bug and some other opportunities for improvements, so I wanted to get some changes in. Everything is mainly about when and how to close tabs.

# Changes

- **Bug fix**: opening a repl while one was already open in the second row got rid of the layout and reverted to a single-cell layout due to the close event. The intended behavior is to keep the row there, close the existing repl, and open a new one in its place. To fix this, change the setting to avoid running the close event during the Open REPL command.
- Only close repl tabs in the second row, ignore other files
- Only remove second row if repl is still in that group on close
- Put new repl in same spot as old repl if one exists, in case there were multiple files in the group

2020-09-23 16:08 UTC, mandeep commented
Thanks for the fixes. Regarding the opening a RELP if one already exsits, I think that a new REPL should open in another tab. This would mimic the behavior or SublimeREPL.

2020-09-23 16:10 UTC, mandeep commented
Also, I think we should default to Python syntax in the REPL rather than plaintext. This would also be the same behavior as SublimeREPL.

2020-09-25 02:52 UTC, mandeep commented
Another thing is that the `Packages` portion of the syntax selection should be a part of the path in the file. That way the user only needs to write `Text/Plain text.tmLanguage` or `Python/Python.tmLanguage`. Or, you could simply let the user chose `plaintext` or `python` and select the corresponding syntax accordingly.

2020-09-25 14:14 UTC, mandeep commented
I noticed another bug. If you have a file open and repl open on the bottom row from a previous session, when opening a new file, the file opens in the second row. It should open in the first row.

2020-09-26 18:34 UTC, gseastream commented
Thanks for the notes. For your last comment, I think that's default sublime behavior. When I have a repl open, if my focus is on the main file and I open a new file, it shows up in the top row, but if I open a file while my focus is in the bottom row repl, the file opens in the bottom row. Sublime opens files in the group where your focus is I'm pretty sure. Is this what you're experiencing? Or are you saying it opens new files in the second row no matter where your focus is?

2020-09-26 18:37 UTC, mandeep commented
You're right, it's based on focus so don't worry about it. :)

2020-09-26 18:39 UTC, mandeep requested changes

2020-09-26 18:39 UTC, mandeep commented on commands.py
> +            syntaxpath = syntaxpath % "Text/Plain text"
We should be using `.format()` syntax rather than `%` syntax for string formatting.

2020-09-26 18:39 UTC, mandeep commented on commands.py
> +            raise ValueError("Unrecognized syntax setting '%s'" % (syntax,))
We want to avoid raising an error at all costs. Instead of raising a `ValueError` we should just print something to debug output.

2020-09-27 05:08 UTC, mandeep commented
Thanks for taking the time to make the changes. One last thing I forgot to mention is that the new repl settings in the settings file should come after the pythonw setting. As we add new settings they appear last in the file.

2020-09-27 16:48 UTC, mandeep approved these changes

2020-09-27 16:53 UTC, mandeep commented
Thanks @gseastream for all your work on this!

2020-09-27 16:53 UTC, merged